package com.danieldigiovanni.parser.exception;

import com.danieldigiovanni.token.Token;

/**
 * Exception representing the case where the parser was given an empty list of
 * tokens.
 */
public class EmptyTokenListParseException extends LoxParseException {

    /**
     * Construct a {@link EmptyTokenListParseException} exception. The token
     * that caused the exception
     * ({@link com.danieldigiovanni.token.TokenType#UNKNOWN} at line 1) will be
     * generated by this constructor.
     */
    public EmptyTokenListParseException() {
        super(Token.unknown(1), "No tokens were given to the parser");
    }

}
