package com.danieldigiovanni.parser.exception;

import com.danieldigiovanni.token.Token;

/**
 * Exception representing an unknown exception.
 */
public class UnknownParseException extends LoxParseException {

    /**
     * Construct a {@link UnknownParseException} exception. The token
     * that caused the exception
     * ({@link com.danieldigiovanni.token.TokenType#UNKNOWN} at line 1) will be
     * generated by this constructor.
     */
    public UnknownParseException() {
        super(
            Token.unknown(1),
            "The parser could not parse the tokens and it doesn't know why :("
        );
    }

}
